apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-react-app
spec:
  selector:
    matchLabels:
      app: pokemon-react-app
  template:
    metadata:
      labels:
        app: pokemon-react-app
    spec:
      containers:
      - name: pokemon-react-app
        image: ramirocastillo93/pokemon-react-app-image:v0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
