apiVersion: v1
kind: Service
metadata:
  name: pokemon-react-app-svc
spec:
  type: NodePort
  selector:
    app: pokemon-react-app
  ports:
  - name: pokemon-react-app-svc-port
    port: 8080
    targetPort: 80
